sudo: false
language: scala
scala:
  - 2.11.7
addons:
  apt:
    packages:
      - libc6-i386
      - lib32z1
      - lib32stdc++6
before_install:
  - openssl aes-256-cbc -k "$encrypted_key" -in debug-keys.tar.enc -out debug-keys.tar -d
  - tar xvf debug-keys.tar
  - mv local.properties modules/app/local.properties
  - wget http://dl.google.com/android/android-sdk_r24-linux.tgz
  - tar xf android-sdk_r24-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ANDROID_SDK_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo yes | android update sdk --all --filter platform-tools --no-ui
  - echo yes | android update sdk --all --filter build-tools-23.0.1 --no-ui
  - echo yes | android update sdk --all --filter android-23 --no-ui
  - echo yes | android update sdk --all --filter extra-android-support --no-ui
  - echo yes | android update sdk --all --filter extra-android-m2repository --no-ui
  - echo yes | android update sdk --all --filter extra-google-m2repository --no-ui
  - export GIT_BRANCH=${TRAVIS_BRANCH}
  - export GIT_PR=${TRAVIS_PULL_REQUEST}
  - export GIT_COMMIT=${TRAVIS_COMMIT}
  - pip install --user codecov && codecov -t ${CODECOV_TOKEN}
script:
#  - sbt ++$TRAVIS_SCALA_VERSION "project commons" coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION "project api" coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION "project repository" coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION "project services" coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION "project process" coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION "project app" coverage test
after_success:
#  - sbt ++$TRAVIS_SCALA_VERSION "project tests" test:coverageAggregate
#  - codecov
  - test ${TRAVIS_BRANCH} == "master" && sbt -mem 4096 ++$TRAVIS_SCALA_VERSION "project app" android:packageRelease
#  - test ${TRAVIS_BRANCH} == "master" && sbt ++$TRAVIS_SCALA_VERSION "project app" s3-upload
#  - test ${TRAVIS_BRANCH} == "master" && sbt ++$TRAVIS_SCALA_VERSION "project app" s3-generateLink
